apiVersion: apps/v1
kind: Deployment
metadata:
  name: rate-user
  namespace: prpo-microservices
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rate-user
  template:
    metadata:
      labels:
        app: rate-user
    spec:
      containers:
      - name: rate-user
        image: prporegistry.azurecr.io/rateuser-app:latest 
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: rate-user-service
  namespace: prpo-microservices
spec:
  type: ClusterIP
  selector:
    app: rate-user-service
  ports:
  - port: 80
    targetPort: 3000
