apiVersion: apps/v1
kind: Deployment
metadata:
  name: rate-user
  namespace: prpo-microservices
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rate-user
  template:
    metadata:
      labels:
        app: rate-user
    spec:
      containers:
        - name: rate-user
          image: prporegistry.azurecr.io/rateuser-app:4134b950490bd5203b78c18d66119ff35bf6346e
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: DB_HOST
              value: "rateuser-db"
            - name: DB_PORT
              value: "5432"
            - name: DB_NAME
              value: "rateuser"
            - name: DB_USER
              value: "rateuser"
            - name: DB_PASSWORD
              value: "rateuser"
      livenessProbe:
        httpGet:
          path: /health/live
          port: 8080
        initialDelaySeconds: 60
        periodSeconds: 10
        timeoutSeconds: 5
        failureThreshold: 3
      startupProbe:
        httpGet:
          path: /health/live
          port: 8080
        initialDelaySeconds: 0
        periodSeconds: 10
        timeoutSeconds: 3
        failureThreshold: 12  

apiVersion: v1
kind: Service
metadata:
  name: rate-user-service
  namespace: prpo-microservices
spec:
  type: ClusterIP
  selector:
    app: rate-user
  ports:
    - port: 80
      targetPort: 8080