apiVersion: apps/v1
kind: Deployment
metadata:
  name: rate-user
  namespace: prpo-microservices
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rate-user
  template:
    metadata:
      labels:
        app: rate-user
    spec:
      containers:
        - name: rate-user
          image: prporegistry.azurecr.io/rateuser-app:ab27f3b8637cfbf9052e6ac8d9fccfeaa73dc10d
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: DB_HOST
              value: "rateuser-db"
            - name: DB_PORT
              value: "5432"
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: rateuser-secret 
                  key: DB_USER
            
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name:  rateuser-secret
                  key: DB_PASSWORD
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: rateuser-secret 
                  key: DB_NAME
      livenessProbe:
        httpGet:
          path: /api/ratings/health/live
          port: 8080
        initialDelaySeconds: 60
        periodSeconds: 10
        timeoutSeconds: 5
        failureThreshold: 3
      startupProbe:
        httpGet:
          path: /api/ratings/health/live
          port: 8080
        initialDelaySeconds: 0
        periodSeconds: 10
        timeoutSeconds: 3
        failureThreshold: 12  

apiVersion: v1
kind: Service
metadata:
  name: rate-user-service
  namespace: prpo-microservices
spec:
  type: ClusterIP
  selector:
    app: rate-user
  ports:
    - port: 80
      targetPort: 8080