apiVersion: apps/v1
kind: Deployment
metadata:
  name: rateuser-app
  namespace: prpo-microservices
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rateuser-app
  template:
    metadata:
      labels:
        app: rateuser-app
    spec:
      containers:
        - name: payara
          image: payara/micro:latest
          ports:
            - containerPort: 8080
          env:
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: rateuser-db
                  key: DB_HOST
            - name: DB_PORT
              value: 5432
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: rateuser-db
                  key: DB_NAME
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: rateuser-db
                  key: DB_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: rateuser-db
                  key: DB_PASSWORD
---
apiVersion: v1
kind: Service
metadata:
  name: rateuser-app
  namespace: prpo-microservices
spec:
  type: ClusterIP
  selector:
    app: rateuser-app
  ports:
    - port: 8080
      targetPort: 8080

