apiVersion: v1
kind: Service
metadata:
  name: rateuser-db
  namespace: prpo-microservices
spec:
  selector:
    app: rateuser-db
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  type: ClusterIP

